-- Guess Who: Digital Edition — Supabase Room schema
-- Run this entire file once in: Supabase Dashboard → SQL Editor → New query.
-- Safe to re-run: tables, indexes, and the trigger are created idempotently.
--
-- Privacy model:
--   * Browser clients receive Room snapshots only from this app's server.
--   * The app server calls Supabase with the server-only service_role key.
--   * RLS is enabled and no browser-facing policies are created, so anon and
--     authenticated clients cannot read Room secrets, seat state, or tokens.

begin;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  open_id varchar(64) not null unique,
  name text,
  email varchar(320),
  login_method varchar(64),
  role varchar(16) not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  room_code varchar(6) not null unique,
  status varchar(24) not null default 'waiting'
    check (status in ('waiting', 'setup', 'secret_selection', 'playing', 'finished', 'expired')),
  settings jsonb not null check (jsonb_typeof(settings) = 'object'),
  deck_ids jsonb not null check (jsonb_typeof(deck_ids) = 'array'),
  deck_seed varchar(64) not null,
  active_seat smallint check (active_seat in (1, 2)),
  winner_seat smallint check (winner_seat in (1, 2)),
  win_reason varchar(16) check (win_reason in ('guess', 'hearts')),
  feedback varchar(255),
  player1_score integer not null default 0 check (player1_score >= 0),
  player2_score integer not null default 0 check (player2_score >= 0),
  revision integer not null default 1 check (revision >= 1),
  created_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  expires_at timestamptz not null,
  constraint rooms_code_format_check check (room_code ~ '^[A-HJ-NP-Z2-9]{6}$')
);

create table if not exists public.seats (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  seat_number smallint not null check (seat_number in (1, 2)),
  player_name varchar(32) not null check (char_length(btrim(player_name)) between 1 and 32),
  secret_card_id integer,
  eliminated_ids jsonb not null default '[]'::jsonb check (jsonb_typeof(eliminated_ids) = 'array'),
  hearts smallint check (hearts between 0 and 5),
  ready boolean not null default false,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint seats_room_seat_unique unique (room_id, seat_number)
);

create table if not exists public.seat_tokens (
  id bigint generated by default as identity primary key,
  token_hash varchar(64) not null unique check (token_hash ~ '^[a-f0-9]{64}$'),
  room_id bigint not null references public.rooms(id) on delete cascade,
  seat_number smallint not null check (seat_number in (1, 2)),
  tab_id varchar(128) not null check (char_length(btrim(tab_id)) between 1 and 128),
  created_at timestamptz not null default now(),
  last_used_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists rooms_status_activity_idx
  on public.rooms (status, last_activity_at);
create index if not exists seats_room_idx
  on public.seats (room_id);
create index if not exists seat_tokens_room_seat_idx
  on public.seat_tokens (room_id, seat_number);
create index if not exists seat_tokens_expires_idx
  on public.seat_tokens (expires_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

-- Defense in depth: direct browser access is denied. The server-side
-- service_role key bypasses RLS and is the only application credential
-- permitted to read or mutate gameplay state.
alter table public.users enable row level security;
alter table public.rooms enable row level security;
alter table public.seats enable row level security;
alter table public.seat_tokens enable row level security;

revoke all on table public.users, public.rooms, public.seats, public.seat_tokens
  from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.users, public.rooms, public.seats, public.seat_tokens
  to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Makes newly-created tables visible to the Supabase REST schema cache.
notify pgrst, 'reload schema';

commit;

-- Expected after a successful run: exactly these four rows are returned.
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in ('users', 'rooms', 'seats', 'seat_tokens')
order by table_name;
