// DESIGN PHILOSOPHY: Whimsical Tabletop Editorial — cards should feel tactile, distinct, and instantly readable when struck out.
// Whimsical Tabletop Editorial: keep category-specific art behavior isolated so
// the approved Fictional Characters treatment remains unchanged.
import { useState } from "react";
import type { GameItem } from "@/data/gameItems";
import { CATEGORY_META } from "@/data/categories";
import { gameAssetUrl } from "@/lib/gameAssetUrl";
import { Check, CircleHelp, X } from "lucide-react";
export function GameCard({ item, eliminated, selectable = true, guessMode = false, onClick }: { item: GameItem; eliminated: boolean; selectable?: boolean; guessMode?: boolean; onClick: () => void }) { const [imageFailed, setImageFailed] = useState(false); const meta = CATEGORY_META[item.category]; const isEmoji = item.category === "emojis"; const showImage = item.artStatus === "generated" && !imageFailed && !isEmoji; const isAnimal = item.category === "animals"; const isCartoon = item.category === "cartoon_characters"; const imageUrl = gameAssetUrl(item.imageUrl); return <button type="button" className={`game-card category-${item.category} ${isEmoji ? "is-emoji" : ""} ${isAnimal ? "is-animal" : ""} ${isCartoon ? "is-cartoon" : ""} ${eliminated ? "is-eliminated" : ""} ${guessMode ? "is-guessable" : ""}`} style={{ "--category-color": meta.color, "--category-soft": meta.soft } as React.CSSProperties} onClick={onClick} disabled={!selectable} aria-pressed={eliminated} aria-label={`${item.name}${eliminated ? ", eliminated" : ""}`}> <span className="card-art">{isEmoji ? <span className="emoji-art" aria-hidden="true">{item.emoji}</span> : showImage ? <img src={imageUrl} alt={`${item.name} illustrated card`} draggable="false" onError={() => setImageFailed(true)} /> : <span className="art-unavailable" aria-hidden="true" />}{showImage ? <span className="card-swatch" aria-hidden="true" /> : null}</span><span className="card-label"><span>{item.name}</span>{guessMode && <CircleHelp size={15} aria-hidden="true" />}</span>{eliminated && <span className="strike-stamp" aria-hidden="true"><X size={34} strokeWidth={3} /></span>}{!eliminated && guessMode && <span className="guess-corner" aria-hidden="true"><Check size={14} /></span>}</button>; }
